package composedaisyui

public object Daisy {
  public object ThemeColor {
    public val Primary: DaisyToken = cls("primary")
    public val PrimaryContent: DaisyToken = cls("primary-content")
    public val Secondary: DaisyToken = cls("secondary")
    public val SecondaryContent: DaisyToken = cls("secondary-content")
    public val Accent: DaisyToken = cls("accent")
    public val AccentContent: DaisyToken = cls("accent-content")
    public val Neutral: DaisyToken = cls("neutral")
    public val NeutralContent: DaisyToken = cls("neutral-content")
    public val Base100: DaisyToken = cls("base-100")
    public val Base200: DaisyToken = cls("base-200")
    public val Base300: DaisyToken = cls("base-300")
    public val BaseContent: DaisyToken = cls("base-content")
    public val Info: DaisyToken = cls("info")
    public val InfoContent: DaisyToken = cls("info-content")
    public val Success: DaisyToken = cls("success")
    public val SuccessContent: DaisyToken = cls("success-content")
    public val Warning: DaisyToken = cls("warning")
    public val WarningContent: DaisyToken = cls("warning-content")
    public val Error: DaisyToken = cls("error")
    public val ErrorContent: DaisyToken = cls("error-content")
  }

  public object Accordion {
    public val Collapse: DaisyToken = cls("collapse")
    public val Title: DaisyToken = cls("collapse-title")
    public val Content: DaisyToken = cls("collapse-content")
    public val Arrow: DaisyToken = cls("collapse-arrow")
    public val Plus: DaisyToken = cls("collapse-plus")
    public val Open: DaisyToken = cls("collapse-open")
    public val Close: DaisyToken = cls("collapse-close")
  }

  public object Alert {
    public val Alert: DaisyToken = cls("alert")
    public val Outline: DaisyToken = cls("alert-outline")
    public val Dash: DaisyToken = cls("alert-dash")
    public val Soft: DaisyToken = cls("alert-soft")
    public val Info: DaisyToken = cls("alert-info")
    public val Success: DaisyToken = cls("alert-success")
    public val Warning: DaisyToken = cls("alert-warning")
    public val Error: DaisyToken = cls("alert-error")
    public val Vertical: DaisyToken = cls("alert-vertical")
    public val Horizontal: DaisyToken = cls("alert-horizontal")
  }

  public object Avatar {
    public val Avatar: DaisyToken = cls("avatar")
    public val Group: DaisyToken = cls("avatar-group")
    public val Online: DaisyToken = cls("avatar-online")
    public val Offline: DaisyToken = cls("avatar-offline")
    public val Placeholder: DaisyToken = cls("avatar-placeholder")
  }

  public object Badge {
    public val Badge: DaisyToken = cls("badge")
    public val Outline: DaisyToken = cls("badge-outline")
    public val Dash: DaisyToken = cls("badge-dash")
    public val Soft: DaisyToken = cls("badge-soft")
    public val Ghost: DaisyToken = cls("badge-ghost")
    public val Neutral: DaisyToken = cls("badge-neutral")
    public val Primary: DaisyToken = cls("badge-primary")
    public val Secondary: DaisyToken = cls("badge-secondary")
    public val Accent: DaisyToken = cls("badge-accent")
    public val Info: DaisyToken = cls("badge-info")
    public val Success: DaisyToken = cls("badge-success")
    public val Warning: DaisyToken = cls("badge-warning")
    public val Error: DaisyToken = cls("badge-error")
    public val Xs: DaisyToken = cls("badge-xs")
    public val Sm: DaisyToken = cls("badge-sm")
    public val Md: DaisyToken = cls("badge-md")
    public val Lg: DaisyToken = cls("badge-lg")
    public val Xl: DaisyToken = cls("badge-xl")
  }

  public object Button {
    public val Btn: DaisyToken = cls("btn")
    public val Neutral: DaisyToken = cls("btn-neutral")
    public val Primary: DaisyToken = cls("btn-primary")
    public val Secondary: DaisyToken = cls("btn-secondary")
    public val Accent: DaisyToken = cls("btn-accent")
    public val Info: DaisyToken = cls("btn-info")
    public val Success: DaisyToken = cls("btn-success")
    public val Warning: DaisyToken = cls("btn-warning")
    public val Error: DaisyToken = cls("btn-error")
    public val Outline: DaisyToken = cls("btn-outline")
    public val Dash: DaisyToken = cls("btn-dash")
    public val Soft: DaisyToken = cls("btn-soft")
    public val Ghost: DaisyToken = cls("btn-ghost")
    public val Link: DaisyToken = cls("btn-link")
    public val Active: DaisyToken = cls("btn-active")
    public val Disabled: DaisyToken = cls("btn-disabled")
    public val Xs: DaisyToken = cls("btn-xs")
    public val Sm: DaisyToken = cls("btn-sm")
    public val Md: DaisyToken = cls("btn-md")
    public val Lg: DaisyToken = cls("btn-lg")
    public val Xl: DaisyToken = cls("btn-xl")
    public val Wide: DaisyToken = cls("btn-wide")
    public val Block: DaisyToken = cls("btn-block")
    public val Square: DaisyToken = cls("btn-square")
    public val Circle: DaisyToken = cls("btn-circle")
  }

  public object Card {
    public val Card: DaisyToken = cls("card")
    public val Title: DaisyToken = cls("card-title")
    public val Body: DaisyToken = cls("card-body")
    public val Actions: DaisyToken = cls("card-actions")
    public val Border: DaisyToken = cls("card-border")
    public val Dash: DaisyToken = cls("card-dash")
    public val Side: DaisyToken = cls("card-side")
    public val ImageFull: DaisyToken = cls("image-full")
    public val Xs: DaisyToken = cls("card-xs")
    public val Sm: DaisyToken = cls("card-sm")
    public val Md: DaisyToken = cls("card-md")
    public val Lg: DaisyToken = cls("card-lg")
    public val Xl: DaisyToken = cls("card-xl")
  }

  public object Form {
    public val Calendar: DaisyToken = cls("calendar")
    public val Checkbox: DaisyToken = cls("checkbox")
    public val CheckboxNeutral: DaisyToken = cls("checkbox-neutral")
    public val CheckboxPrimary: DaisyToken = cls("checkbox-primary")
    public val CheckboxSecondary: DaisyToken = cls("checkbox-secondary")
    public val CheckboxAccent: DaisyToken = cls("checkbox-accent")
    public val CheckboxInfo: DaisyToken = cls("checkbox-info")
    public val CheckboxSuccess: DaisyToken = cls("checkbox-success")
    public val CheckboxWarning: DaisyToken = cls("checkbox-warning")
    public val CheckboxError: DaisyToken = cls("checkbox-error")
    public val CheckboxXs: DaisyToken = cls("checkbox-xs")
    public val CheckboxSm: DaisyToken = cls("checkbox-sm")
    public val CheckboxMd: DaisyToken = cls("checkbox-md")
    public val CheckboxLg: DaisyToken = cls("checkbox-lg")
    public val CheckboxXl: DaisyToken = cls("checkbox-xl")
    public val Radio: DaisyToken = cls("radio")
    public val RadioNeutral: DaisyToken = cls("radio-neutral")
    public val RadioPrimary: DaisyToken = cls("radio-primary")
    public val RadioSecondary: DaisyToken = cls("radio-secondary")
    public val RadioAccent: DaisyToken = cls("radio-accent")
    public val RadioInfo: DaisyToken = cls("radio-info")
    public val RadioSuccess: DaisyToken = cls("radio-success")
    public val RadioWarning: DaisyToken = cls("radio-warning")
    public val RadioError: DaisyToken = cls("radio-error")
    public val RadioXs: DaisyToken = cls("radio-xs")
    public val RadioSm: DaisyToken = cls("radio-sm")
    public val RadioMd: DaisyToken = cls("radio-md")
    public val RadioLg: DaisyToken = cls("radio-lg")
    public val RadioXl: DaisyToken = cls("radio-xl")
    public val Toggle: DaisyToken = cls("toggle")
    public val ToggleNeutral: DaisyToken = cls("toggle-neutral")
    public val TogglePrimary: DaisyToken = cls("toggle-primary")
    public val ToggleSecondary: DaisyToken = cls("toggle-secondary")
    public val ToggleAccent: DaisyToken = cls("toggle-accent")
    public val ToggleInfo: DaisyToken = cls("toggle-info")
    public val ToggleSuccess: DaisyToken = cls("toggle-success")
    public val ToggleWarning: DaisyToken = cls("toggle-warning")
    public val ToggleError: DaisyToken = cls("toggle-error")
    public val ToggleXs: DaisyToken = cls("toggle-xs")
    public val ToggleSm: DaisyToken = cls("toggle-sm")
    public val ToggleMd: DaisyToken = cls("toggle-md")
    public val ToggleLg: DaisyToken = cls("toggle-lg")
    public val ToggleXl: DaisyToken = cls("toggle-xl")
    public val Range: DaisyToken = cls("range")
    public val RangeNeutral: DaisyToken = cls("range-neutral")
    public val RangePrimary: DaisyToken = cls("range-primary")
    public val RangeSecondary: DaisyToken = cls("range-secondary")
    public val RangeAccent: DaisyToken = cls("range-accent")
    public val RangeInfo: DaisyToken = cls("range-info")
    public val RangeSuccess: DaisyToken = cls("range-success")
    public val RangeWarning: DaisyToken = cls("range-warning")
    public val RangeError: DaisyToken = cls("range-error")
    public val RangeXs: DaisyToken = cls("range-xs")
    public val RangeSm: DaisyToken = cls("range-sm")
    public val RangeMd: DaisyToken = cls("range-md")
    public val RangeLg: DaisyToken = cls("range-lg")
    public val RangeXl: DaisyToken = cls("range-xl")
    public val Input: DaisyToken = cls("input")
    public val InputGhost: DaisyToken = cls("input-ghost")
    public val Select: DaisyToken = cls("select")
    public val SelectGhost: DaisyToken = cls("select-ghost")
    public val Textarea: DaisyToken = cls("textarea")
    public val TextareaGhost: DaisyToken = cls("textarea-ghost")
    public val FileInput: DaisyToken = cls("file-input")
    public val FileInputGhost: DaisyToken = cls("file-input-ghost")
    public val Label: DaisyToken = cls("label")
    public val FloatingLabel: DaisyToken = cls("floating-label")
    public val Fieldset: DaisyToken = cls("fieldset")
    public val FieldsetLegend: DaisyToken = cls("fieldset-legend")
    public val Filter: DaisyToken = cls("filter")
    public val FilterReset: DaisyToken = cls("filter-reset")
    public val ThemeController: DaisyToken = cls("theme-controller")
    public val Validator: DaisyToken = cls("validator")
    public val ValidatorHint: DaisyToken = cls("validator-hint")
  }

  public object Layout {
    public val Breadcrumbs: DaisyToken = cls("breadcrumbs")
    public val Divider: DaisyToken = cls("divider")
    public val DividerVertical: DaisyToken = cls("divider-vertical")
    public val DividerHorizontal: DaisyToken = cls("divider-horizontal")
    public val DividerStart: DaisyToken = cls("divider-start")
    public val DividerEnd: DaisyToken = cls("divider-end")
    public val Drawer: DaisyToken = cls("drawer")
    public val DrawerToggle: DaisyToken = cls("drawer-toggle")
    public val DrawerContent: DaisyToken = cls("drawer-content")
    public val DrawerSide: DaisyToken = cls("drawer-side")
    public val DrawerOverlay: DaisyToken = cls("drawer-overlay")
    public val DrawerEnd: DaisyToken = cls("drawer-end")
    public val DrawerOpen: DaisyToken = cls("drawer-open")
    public val Footer: DaisyToken = cls("footer")
    public val FooterTitle: DaisyToken = cls("footer-title")
    public val FooterCenter: DaisyToken = cls("footer-center")
    public val FooterHorizontal: DaisyToken = cls("footer-horizontal")
    public val FooterVertical: DaisyToken = cls("footer-vertical")
    public val Hero: DaisyToken = cls("hero")
    public val HeroContent: DaisyToken = cls("hero-content")
    public val HeroOverlay: DaisyToken = cls("hero-overlay")
    public val Indicator: DaisyToken = cls("indicator")
    public val IndicatorItem: DaisyToken = cls("indicator-item")
    public val Join: DaisyToken = cls("join")
    public val JoinItem: DaisyToken = cls("join-item")
    public val JoinVertical: DaisyToken = cls("join-vertical")
    public val JoinHorizontal: DaisyToken = cls("join-horizontal")
    public val Navbar: DaisyToken = cls("navbar")
    public val NavbarStart: DaisyToken = cls("navbar-start")
    public val NavbarCenter: DaisyToken = cls("navbar-center")
    public val NavbarEnd: DaisyToken = cls("navbar-end")
    public val Stack: DaisyToken = cls("stack")
    public val StackTop: DaisyToken = cls("stack-top")
    public val StackBottom: DaisyToken = cls("stack-bottom")
    public val StackStart: DaisyToken = cls("stack-start")
    public val StackEnd: DaisyToken = cls("stack-end")
  }

  public object Feedback {
    public val Loading: DaisyToken = cls("loading")
    public val LoadingSpinner: DaisyToken = cls("loading-spinner")
    public val LoadingDots: DaisyToken = cls("loading-dots")
    public val LoadingRing: DaisyToken = cls("loading-ring")
    public val LoadingBall: DaisyToken = cls("loading-ball")
    public val LoadingBars: DaisyToken = cls("loading-bars")
    public val LoadingInfinity: DaisyToken = cls("loading-infinity")
    public val Progress: DaisyToken = cls("progress")
    public val RadialProgress: DaisyToken = cls("radial-progress")
    public val Skeleton: DaisyToken = cls("skeleton")
    public val SkeletonText: DaisyToken = cls("skeleton-text")
    public val Status: DaisyToken = cls("status")
    public val Toast: DaisyToken = cls("toast")
    public val Tooltip: DaisyToken = cls("tooltip")
    public val TooltipContent: DaisyToken = cls("tooltip-content")
    public val TooltipOpen: DaisyToken = cls("tooltip-open")
  }

  public object Navigation {
    public val Dock: DaisyToken = cls("dock")
    public val DockLabel: DaisyToken = cls("dock-label")
    public val DockActive: DaisyToken = cls("dock-active")
    public val Dropdown: DaisyToken = cls("dropdown")
    public val DropdownContent: DaisyToken = cls("dropdown-content")
    public val DropdownHover: DaisyToken = cls("dropdown-hover")
    public val DropdownOpen: DaisyToken = cls("dropdown-open")
    public val DropdownClose: DaisyToken = cls("dropdown-close")
    public val Menu: DaisyToken = cls("menu")
    public val MenuHorizontal: DaisyToken = cls("menu-horizontal")
    public val MenuVertical: DaisyToken = cls("menu-vertical")
    public val MenuTitle: DaisyToken = cls("menu-title")
    public val MenuDropdown: DaisyToken = cls("menu-dropdown")
    public val MenuDropdownToggle: DaisyToken = cls("menu-dropdown-toggle")
    public val MenuDisabled: DaisyToken = cls("menu-disabled")
    public val MenuActive: DaisyToken = cls("menu-active")
    public val MenuFocus: DaisyToken = cls("menu-focus")
    public val MenuDropdownShow: DaisyToken = cls("menu-dropdown-show")
    public val Steps: DaisyToken = cls("steps")
    public val StepsHorizontal: DaisyToken = cls("steps-horizontal")
    public val StepsVertical: DaisyToken = cls("steps-vertical")
    public val Step: DaisyToken = cls("step")
    public val StepIcon: DaisyToken = cls("step-icon")
    public val Tabs: DaisyToken = cls("tabs")
    public val TabsBox: DaisyToken = cls("tabs-box")
    public val TabsBorder: DaisyToken = cls("tabs-border")
    public val TabsLift: DaisyToken = cls("tabs-lift")
    public val TabsTop: DaisyToken = cls("tabs-top")
    public val TabsBottom: DaisyToken = cls("tabs-bottom")
    public val Tab: DaisyToken = cls("tab")
    public val TabContent: DaisyToken = cls("tab-content")
    public val TabActive: DaisyToken = cls("tab-active")
    public val TabDisabled: DaisyToken = cls("tab-disabled")
  }

  public object Data {
    public val Kbd: DaisyToken = cls("kbd")
    public val List: DaisyToken = cls("list")
    public val ListRow: DaisyToken = cls("list-row")
    public val ListColGrow: DaisyToken = cls("list-col-grow")
    public val ListColWrap: DaisyToken = cls("list-col-wrap")
    public val Stat: DaisyToken = cls("stat")
    public val Stats: DaisyToken = cls("stats")
    public val StatsHorizontal: DaisyToken = cls("stats-horizontal")
    public val StatsVertical: DaisyToken = cls("stats-vertical")
    public val StatTitle: DaisyToken = cls("stat-title")
    public val StatValue: DaisyToken = cls("stat-value")
    public val StatDesc: DaisyToken = cls("stat-desc")
    public val StatFigure: DaisyToken = cls("stat-figure")
    public val StatActions: DaisyToken = cls("stat-actions")
    public val Table: DaisyToken = cls("table")
    public val TableZebra: DaisyToken = cls("table-zebra")
    public val TablePinRows: DaisyToken = cls("table-pin-rows")
    public val TablePinCols: DaisyToken = cls("table-pin-cols")
    public val Timeline: DaisyToken = cls("timeline")
    public val TimelineHorizontal: DaisyToken = cls("timeline-horizontal")
    public val TimelineVertical: DaisyToken = cls("timeline-vertical")
    public val TimelineStart: DaisyToken = cls("timeline-start")
    public val TimelineMiddle: DaisyToken = cls("timeline-middle")
    public val TimelineEnd: DaisyToken = cls("timeline-end")
    public val TimelineSnapIcon: DaisyToken = cls("timeline-snap-icon")
    public val TimelineBox: DaisyToken = cls("timeline-box")
    public val TimelineCompact: DaisyToken = cls("timeline-compact")
  }

  public object Display {
    public val Carousel: DaisyToken = cls("carousel")
    public val CarouselItem: DaisyToken = cls("carousel-item")
    public val CarouselStart: DaisyToken = cls("carousel-start")
    public val CarouselCenter: DaisyToken = cls("carousel-center")
    public val CarouselEnd: DaisyToken = cls("carousel-end")
    public val CarouselHorizontal: DaisyToken = cls("carousel-horizontal")
    public val CarouselVertical: DaisyToken = cls("carousel-vertical")
    public val Chat: DaisyToken = cls("chat")
    public val ChatStart: DaisyToken = cls("chat-start")
    public val ChatEnd: DaisyToken = cls("chat-end")
    public val ChatImage: DaisyToken = cls("chat-image")
    public val ChatHeader: DaisyToken = cls("chat-header")
    public val ChatFooter: DaisyToken = cls("chat-footer")
    public val ChatBubble: DaisyToken = cls("chat-bubble")
    public val ChatBubbleNeutral: DaisyToken = cls("chat-bubble-neutral")
    public val ChatBubblePrimary: DaisyToken = cls("chat-bubble-primary")
    public val ChatBubbleSecondary: DaisyToken = cls("chat-bubble-secondary")
    public val ChatBubbleAccent: DaisyToken = cls("chat-bubble-accent")
    public val ChatBubbleInfo: DaisyToken = cls("chat-bubble-info")
    public val ChatBubbleSuccess: DaisyToken = cls("chat-bubble-success")
    public val ChatBubbleWarning: DaisyToken = cls("chat-bubble-warning")
    public val ChatBubbleError: DaisyToken = cls("chat-bubble-error")
    public val Collapse: DaisyToken = cls("collapse")
    public val Countdown: DaisyToken = cls("countdown")
    public val Diff: DaisyToken = cls("diff")
    public val DiffItem1: DaisyToken = cls("diff-item-1")
    public val DiffItem2: DaisyToken = cls("diff-item-2")
    public val DiffResizer: DaisyToken = cls("diff-resizer")
    public val Fab: DaisyToken = cls("fab")
    public val FabClose: DaisyToken = cls("fab-close")
    public val FabFlower: DaisyToken = cls("fab-flower")
    public val FabMainAction: DaisyToken = cls("fab-main-action")
    public val Hover3d: DaisyToken = cls("hover-3d")
    public val HoverGallery: DaisyToken = cls("hover-gallery")
    public val Link: DaisyToken = cls("link")
    public val LinkHover: DaisyToken = cls("link-hover")
    public val Mask: DaisyToken = cls("mask")
    public val Modal: DaisyToken = cls("modal")
    public val ModalBox: DaisyToken = cls("modal-box")
    public val ModalAction: DaisyToken = cls("modal-action")
    public val ModalBackdrop: DaisyToken = cls("modal-backdrop")
    public val ModalToggle: DaisyToken = cls("modal-toggle")
    public val ModalOpen: DaisyToken = cls("modal-open")
    public val MockupBrowser: DaisyToken = cls("mockup-browser")
    public val MockupBrowserToolbar: DaisyToken = cls("mockup-browser-toolbar")
    public val MockupCode: DaisyToken = cls("mockup-code")
    public val MockupPhone: DaisyToken = cls("mockup-phone")
    public val MockupPhoneCamera: DaisyToken = cls("mockup-phone-camera")
    public val MockupPhoneDisplay: DaisyToken = cls("mockup-phone-display")
    public val MockupWindow: DaisyToken = cls("mockup-window")
    public val Rating: DaisyToken = cls("rating")
    public val RatingHalf: DaisyToken = cls("rating-half")
    public val RatingHidden: DaisyToken = cls("rating-hidden")
    public val Swap: DaisyToken = cls("swap")
    public val SwapOn: DaisyToken = cls("swap-on")
    public val SwapOff: DaisyToken = cls("swap-off")
    public val SwapIndeterminate: DaisyToken = cls("swap-indeterminate")
    public val SwapRotate: DaisyToken = cls("swap-rotate")
    public val SwapFlip: DaisyToken = cls("swap-flip")
    public val TextRotate: DaisyToken = cls("text-rotate")
  }

  public object Modifier {
    public val Neutral: DaisyToken = cls("neutral")
    public val Primary: DaisyToken = cls("primary")
    public val Secondary: DaisyToken = cls("secondary")
    public val Accent: DaisyToken = cls("accent")
    public val Info: DaisyToken = cls("info")
    public val Success: DaisyToken = cls("success")
    public val Warning: DaisyToken = cls("warning")
    public val Error: DaisyToken = cls("error")
    public val Xs: DaisyToken = cls("xs")
    public val Sm: DaisyToken = cls("sm")
    public val Md: DaisyToken = cls("md")
    public val Lg: DaisyToken = cls("lg")
    public val Xl: DaisyToken = cls("xl")
  }
}
